swagger: '2.0'
info:
  title: API Example Swagger
  description: Example structure of a swagger definition
  version: 1.0.0
host: api.mkp-cr-detail-offers-be.endpoints.mkp-cross-clusters-dev.cloud.goog
security:
- api_key: []
- oauth2_key: []
basePath: /marketplace/sales/v2
tags:
- name: Tag1
  description: Description of Tag1
paths:
  /endpoint:
    get:
      tags:
      - tag1
      - tag2
      summary: Summary
      description: Description
      operationId: getOperationId
      produces:
      - application/json
      parameters:
      - name: X-Application-Id
        in: header
        description: Application ID
        required: true
        type: string
      - name: X-Company-Id
        in: header
        description: Company ID
        required: true
        type: string
      - name: X-User-Id
        in: header
        description: User ID
        required: true
        type: string
      - name: X-Trace-Id
        in: header
        description: Trace ID
        required: true
        type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Root'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        '404':
          description: Data not found
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        '405':
          description: Data input not supplied or invalid
          schema:
            $ref: '#/definitions/ApiErrorResponse'
        '406':
          description: Exception
          schema:
            $ref: '#/definitions/ApiErrorResponse'
      deprecated: false
definitions:
  ObjectError:
    type: object
    description: Error Enitity
    properties:
      code:
        type: string
        description: Id of the technical exception
      message:
        type: string
        description: Technical message
      nativeMessage:
        type: string
        description: Native error message
      trackid:
        type: string
        description: Track id of transaction process
  ApiErrorResponse:
    type: object
    description: Error API responses
    properties:
      code:
        type: string
        description: Internal error ID
      message:
        type: string
        description: Basic message error
      description:
        type: string
        description: Detailed error description
      errors:
        type: array
        description: List of errors
        items:
          $ref: '#/definitions/ObjectError'
  Root:
    type: object
    title: Root
    description: Root Entity
    properties:
      id:
        type: string
        example: ffe74d36-4f76-4ca6-9dd1-8d5c9b16b056
      name:
        type: string
        example: JSON example
      description:
        type: string
        example: Just a simple JSON file to convert into swagger definition
      someObject:
        $ref: '#/definitions/SomeObject'
      items:
        type: array
        items:
          $ref: '#/definitions/Item'
  SomeObject:
    type: object
    title: Some Object
    description: Some Object Entity
    properties:
      someInteger:
        type: integer
        example: 0
      someNumber:
        type: number
        example: 0.1
      someBoolean:
        type: boolean
        example: true
      someNull:
        type: string
        example: null
      someString:
        type: string
        example: Example string content
  Item:
    type: object
    title: Item
    description: Item Entity
    properties:
      name:
        type: string
        example: Item
      subItem:
        $ref: '#/definitions/SubItem'
  SubItem:
    type: object
    title: Sub Item
    description: Sub Item Entity
    properties:
      subItemsOfSubItem:
        type: array
        items:
          $ref: '#/definitions/SubItemsOfSubItem'
  SubItemsOfSubItem:
    type: object
    title: Sub Items Of Sub Item
    description: Sub Items Of Sub Item Entity
    properties:
      foo:
        type: string
        example: lastBar
      secondFoo:
        type: string
        example: secondBar
